let mydate=new Date();
console.log(mydate.getDate());
console.log(mydate.getDay());
console.log(mydate.getFullYear());
console.log(mydate.getHours());
console.log(mydate.getMilliseconds());
console.log(mydate.getMinutes());
console.log(mydate.getSeconds());
console.log(mydate.getTimezoneOffset());
console.log(mydate.getUTCFullYear());
console.log(mydate.toLocaleDateString());
console.log(mydate.toLocaleTimeString());